### ISSUE TITLE
为啥在本地SimpleHTTPServer打开不了？

### ISSUE THREAD

**Issue by jinningli** [woxieao/watermelon#1]
进度条到99就停了。现在这个还能用吗？

**Comment by woxieao** [comment]
原网站更新了资源文件导致的  我也同步更新了 现在可以了 直接部署到web服务器就能耍了

**Comment by jinningli** [comment]
谢谢大佬，我准备加到我的githubpage去

**Comment by jinningli** [comment]
另外想问下资源文件你是怎么获得的？

**Comment by jinningli** [comment]
仿佛资源文件又更新了，我还是打不开。挠头

**Comment by jackect** [comment]
> 仿佛资源文件又更新了，我还是打不开。挠头

我猜测是原网站限制了第三方网站的资源加载

**Comment by jinningli** [comment]
> 我猜测是原网站限制了第三方网站的资源加载

有可能。但是有没有办法突破限制呢

**Comment by jinningli** [comment]
现在的版本能用了。

**Comment by lyyy666** [comment]
> 现在的版本能用了。

你好~想问下你部署成功了吗~

**Comment by lyyy666** [comment]
> 现在的版本能用了。

你好~请问你部署成功了嘛~
